package tv.strohi.twitch.strohkoenigbot.chatbot.actions.model;

public enum AbilityType {
	Any,
	AbilityDoubler,
	BombDefenseUpDx,
	Comeback,
	DropRoller,
	Haunt,
	InkRecoveryUp,
	InkResistanceUp,
	InkSaverMain,
	InkSaverSub,
	LastDitchEffort,
	MainPowerUp,
	NinjaSquid,
	ObjectShredder,
	OpeningGambit,
	QuickRespawn,
	QuickSuperJump,
	RespawnPunisher,
	RunSpeedUp,
	SpecialChargeUp,
	SpecialPowerUp,
	SpecialSaver,
	StealthJump,
	SubPowerUp,
	SwimSpeedUp,
	Tenacity,
	ThermalInk
}
