databaseChangeLog:
  - changeSet:
      id: 2026-09-04_02-increase-configuration-name-length
      author: strohkoenig
      changes:
        - modifyDataType:
            tableName: configuration
            columnName: config_name
            newDataType: varchar(200)
